# Generated by Django 5.0.6 on 2024-05-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Zone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_img',
            field=models.ImageField(null=True, upload_to='static/media/vendor_img'),
        ),
    ]
