# Generated by Django 5.0.6 on 2024-06-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Zone', '0002_alter_vendor_vendor_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_img',
            field=models.ImageField(null=True, upload_to='media/vendor_img'),
        ),
    ]
