# Generated by Django 5.0.6 on 2024-06-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Zone', '0003_alter_users_profile_pic_alter_vendor_vendor_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='media/profile_pic'),
        ),
    ]
